global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: connect-ip-tunnel-server
    static_configs:
      - targets:
          - server:9090
    metrics_path: /metrics
